// data.js - لینک‌های اشتراک‌های رایگان
const subscriptionsData = {
    "ایکس ری": {
        "config-fetcher": "https://raw.githubusercontent.com/10ium/multi-proxy-config-fetcher/refs/heads/main/configs/proxy_configs.txt",
        "HiN-VPN hysteria2": "https://raw.githubusercontent.com/10ium/HiN-VPN/main/subscription/normal/hysteria2",
        "HiN-VPN hysteria": "https://raw.githubusercontent.com/10ium/HiN-VPN/main/subscription/normal/hysteria",
        "HiN-VPN tuic": "https://raw.githubusercontent.com/10ium/HiN-VPN/main/subscription/normal/tuic",
        "HiN-VPN trojan": "https://raw.githubusercontent.com/10ium/HiN-VPN/main/subscription/normal/trojan",
        "HiN-VPN ss": "https://raw.githubusercontent.com/10ium/HiN-VPN/main/subscription/normal/ss",
        "HiN-VPN vless": "https://raw.githubusercontent.com/10ium/HiN-VPN/main/subscription/normal/vless",
        "HiN-VPN vmess": "https://raw.githubusercontent.com/10ium/HiN-VPN/main/subscription/normal/vmess",
        "HiN-VPN mix": "hhttps://raw.githubusercontent.com/10ium/HiN-VPN/main/subscription/normal/mix",
        "V2Hub merged": "https://raw.githubusercontent.com/10ium/V2Hub3/main/merged",
        "V2Hub vmess": "https://raw.githubusercontent.com/10ium/V2Hub3/main/Split/Normal/vmess",
        "V2Hub vless": "https://raw.githubusercontent.com/10ium/V2Hub3/main/Split/Normal/vless",
        "V2Hub reality": "https://raw.githubusercontent.com/10ium/V2Hub3/main/Split/Normal/reality",
        "V2Hub trojan": "https://raw.githubusercontent.com/10ium/V2Hub3/main/Split/Normal/trojan",
        "V2Hub shadowsocks": "https://raw.githubusercontent.com/10ium/V2Hub3/main/Split/Normal/shadowsocks",
        "Aggregator": "https://raw.githubusercontent.com/10ium/V2RayAggregator/refs/heads/master/Eternity.txt",
        "CollectorLite vmess": "https://raw.githubusercontent.com/10ium/V2rayCollectorLite/main/vmess_iran.txt",
        "CollectorLite ss": "https://raw.githubusercontent.com/10ium/V2rayCollectorLite/main/ss_iran.txt",
        "CollectorLite trojan": "https://raw.githubusercontent.com/10ium/V2rayCollectorLite/main/trojan_iran.txt",
        "CollectorLite vless": "https://raw.githubusercontent.com/10ium/V2rayCollectorLite/main/vless_iran.txt",
        "CollectorLite mixed": "https://raw.githubusercontent.com/10ium/V2rayCollectorLite/main/mixed_iran.txt",
        "Collector vmess": "https://raw.githubusercontent.com/10ium/V2rayCollector/main/vmess_iran.txt",
        "Collector ss": "https://raw.githubusercontent.com/10ium/V2rayCollector/main/ss_iran.txt",
        "Collector trojan": "https://raw.githubusercontent.com/10ium/V2rayCollector/main/trojan_iran.txt",
        "Collector vless": "https://raw.githubusercontent.com/10ium/V2rayCollector/main/vless_iran.txt",
        "Collector mixed": "https://raw.githubusercontent.com/10ium/V2rayCollector/main/mixed_iran.txt",
        "V2ray-Config All": "https://raw.githubusercontent.com/10ium/V2ray-Config/main/All_Configs_Sub.txt"
    },
    
    "ایکس ری بیس64": {
        "config-fetcher": "https://raw.githubusercontent.com/10ium/base64-encoder/main/encoded/10ium_proxy_configs.txt",
        "HiN-VPN hysteria2": "https://raw.githubusercontent.com/10ium/HiN-VPN/main/subscription/base64/hysteria2",
        "HiN-VPN hysteria": "https://raw.githubusercontent.com/10ium/HiN-VPN/main/subscription/base64/hysteria",
        "HiN-VPN tuic": "https://raw.githubusercontent.com/10ium/HiN-VPN/main/subscription/base64/tuic",
        "HiN-VPN trojan": "https://raw.githubusercontent.com/10ium/HiN-VPN/main/subscription/base64/trojan",
        "HiN-VPN ss": "https://raw.githubusercontent.com/10ium/HiN-VPN/main/subscription/base64/ss",
        "HiN-VPN vless": "https://raw.githubusercontent.com/10ium/HiN-VPN/main/subscription/base64/vless",
        "HiN-VPN vmess": "https://raw.githubusercontent.com/10ium/HiN-VPN/main/subscription/base64/vmess",
        "HiN-VPN mix": "hhttps://raw.githubusercontent.com/10ium/HiN-VPN/main/subscription/base64/mix",
        "MahsaFreeConfig mci 1": "https://raw.githubusercontent.com/mahsanet/MahsaFreeConfig/refs/heads/main/mci/sub_1.txt",
        "MahsaFreeConfig mci 2": "https://raw.githubusercontent.com/mahsanet/MahsaFreeConfig/refs/heads/main/mci/sub_2.txt",
        "MahsaFreeConfig mci 3": "https://raw.githubusercontent.com/mahsanet/MahsaFreeConfig/refs/heads/main/mci/sub_3.txt",
        "MahsaFreeConfig mci 4": "https://raw.githubusercontent.com/mahsanet/MahsaFreeConfig/refs/heads/main/mci/sub_4.txt",
        "MahsaFreeConfig mtn 1": "https://raw.githubusercontent.com/mahsanet/MahsaFreeConfig/refs/heads/main/mtn/sub_1.txt",
        "MahsaFreeConfig mtn 2": "https://raw.githubusercontent.com/mahsanet/MahsaFreeConfig/refs/heads/main/mtn/sub_2.txt",
        "MahsaFreeConfig mtn 3": "https://raw.githubusercontent.com/mahsanet/MahsaFreeConfig/refs/heads/main/mtn/sub_3.txt",
        "MahsaFreeConfig mtn 4": "https://raw.githubusercontent.com/mahsanet/MahsaFreeConfig/refs/heads/main/mtn/sub_4.txt",
        "V2Hub merged": "https://raw.githubusercontent.com/10ium/V2Hub3/main/merged_base64",
        "V2Hub vmess": "https://raw.githubusercontent.com/10ium/V2Hub3/main/Split/Base64/vmess",
        "V2Hub vless": "https://raw.githubusercontent.com/10ium/V2Hub3/main/Split/Base64/vless",
        "V2Hub reality": "https://raw.githubusercontent.com/10ium/V2Hub3/main/Split/Base64/reality",
        "V2Hub trojan": "https://raw.githubusercontent.com/10ium/V2Hub3/main/Split/Base64/trojan",
        "V2Hub shadowsocks": "https://raw.githubusercontent.com/10ium/V2Hub3/main/Split/Base64/shadowsocks",
        "Aggregator": "https://raw.githubusercontent.com/10ium/V2RayAggregator/refs/heads/master/Eternity",
        "CollectorLite vmess": "https://raw.githubusercontent.com/10ium/base64-encoder/main/encoded/10ium_vmess_iran.txt",
        "CollectorLite ss": "https://raw.githubusercontent.com/10ium/base64-encoder/main/encoded/10ium_ss_iran.txt",
        "CollectorLite trojan": "https://raw.githubusercontent.com/10ium/base64-encoder/main/encoded/10ium_trojan_iran.txt",
        "CollectorLite vless": "https://raw.githubusercontent.com/10ium/base64-encoder/main/encoded/10ium_vless_iran.txt",
        "CollectorLite mixed": "https://raw.githubusercontent.com/10ium/base64-encoder/main/encoded/10ium_mixed_iran.txt",
        "Collector mixed": "https://raw.githubusercontent.com/10ium/base64-encoder/main/encoded/10ium-V2rayCollector-mixed.txt",
        "Collector ss": "https://raw.githubusercontent.com/10ium/base64-encoder/main/encoded/10ium-V2rayCollector-ss.txt",
        "Collector trojan": "https://raw.githubusercontent.com/10ium/base64-encoder/main/encoded/10ium-V2rayCollector-trojan.txt",
        "Collector vless": "https://raw.githubusercontent.com/10ium/base64-encoder/main/encoded/10ium-V2rayCollector-vless.txt",
        "Collector vmess": "https://raw.githubusercontent.com/10ium/base64-encoder/main/encoded/10ium-V2rayCollector-vmess.txt",
        "V2ray-Config All": "https://raw.githubusercontent.com/10ium/V2ray-Config/main/All_Configs_base64_Sub.txt",
        "V2ray-Config vmess": "https://raw.githubusercontent.com/10ium/V2ray-Config/main/Splitted-By-Protocol/vmess.txt",
        "V2ray-Config vless": "https://raw.githubusercontent.com/10ium/V2ray-Config/main/Splitted-By-Protocol/vless.txt",
        "V2ray-Config trojan": "https://raw.githubusercontent.com/10ium/V2ray-Config/main/Splitted-By-Protocol/trojan.txt",
        "V2ray-Config ss": "https://raw.githubusercontent.com/10ium/V2ray-Config/main/Splitted-By-Protocol/ss.txt",
        "V2ray-Config ssr": "https://raw.githubusercontent.com/10ium/V2ray-Config/main/Splitted-By-Protocol/ssr.txt",
        "V2ray-Config tuic": "https://raw.githubusercontent.com/10ium/V2ray-Config/main/Splitted-By-Protocol/tuic.txt",
        "V2ray-Config hysteria2": "https://raw.githubusercontent.com/10ium/V2ray-Config/main/Splitted-By-Protocol/hysteria2.txt",
        "rayan_proxy": "https://raw.githubusercontent.com/vpnclashfa-backup/SubConfigShuffler/refs/heads/main/shuffled_outputs/rayan_proxy.txt",
        "roosterkid": "https://raw.githubusercontent.com/vpnclashfa-backup/SubConfigShuffler/refs/heads/main/shuffled_outputs/roosterkid_v2ray.txt",
        "maimengmeng": "https://raw.githubusercontent.com/vpnclashfa-backup/SubConfigShuffler/refs/heads/main/shuffled_outputs/maimengmeng.txt",
        "maimengmeng_AnyTLS": "https://raw.githubusercontent.com/vpnclashfa-backup/SubConfigShuffler/refs/heads/main/shuffled_outputs/maimengmeng_AnyTLS.txt",
        "Juicity - Mixed": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/protocols/juicity",
        "Juicity - Telegram Channels": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/channels/protocols/juicity",
        "Juicity - Links": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/subscribe/protocols/juicity",
        "Hysteria - Mixed": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/protocols/hysteria",
        "Hysteria - Telegram Channels": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/channels/protocols/hysteria",
        "Hysteria - Links": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/subscribe/protocols/hysteria",
        "Tuic - Mixed": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/protocols/tuic",
        "Tuic - Telegram Channels": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/channels/protocols/tuic",
        "Tuic - Links": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/subscribe/protocols/tuic",
        "Reality - Mixed": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/protocols/reality",
        "Reality - Telegram Channels": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/channels/protocols/reality",
        "Reality - Links": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/subscribe/protocols/reality",
        "Vless - Mixed": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/protocols/vless",
        "Vless - Telegram Channels": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/channels/protocols/vless",
        "Vless - Links": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/subscribe/protocols/vless",
        "Vmess - Mixed": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/protocols/vmess",
        "Vmess - Telegram Channels": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/channels/protocols/vmess",
        "Vmess - Links": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/subscribe/protocols/vmess",
        "Trojan - Mixed": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/protocols/trojan",
        "Trojan - Telegram Channels": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/channels/protocols/trojan",
        "Trojan - Links": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/subscribe/protocols/trojan",
        "Shadowsocks - Mixed": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/protocols/shadowsocks",
        "Shadowsocks - Telegram Channels": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/channels/protocols/shadowsocks",
        "Shadowsocks - Links": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/subscribe/protocols/shadowsocks",
        "Mixed Type - Mixed": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/splitted/mixed",
        "Mixed Type - Telegram Channels": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/splitted/channels",
        "Mixed Type - Links": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/splitted/subscribe",
        "Google Remote Procedure Call (GRPC) - Mixed": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/networks/grpc",
        "Google Remote Procedure Call (GRPC) - Telegram Channels": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/channels/networks/grpc",
        "Google Remote Procedure Call (GRPC) - Links": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/subscribe/networks/grpc",
        "Hypertext Transfer Protocol (HTTP) - Mixed": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/networks/http",
        "Hypertext Transfer Protocol (HTTP) - Telegram Channels": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/channels/networks/http",
        "Hypertext Transfer Protocol (HTTP) - Links": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/subscribe/networks/http",
        "WebSocket Protocol (WS) - Mixed": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/networks/ws",
        "WebSocket Protocol (WS) - Telegram Channels": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/channels/networks/ws",
        "WebSocket Protocol (WS) - Links": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/subscribe/networks/ws",
        "Transmission Control Protocol (TCP) - Mixed": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/networks/tcp",
        "Transmission Control Protocol (TCP) - Telegram Channels": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/channels/networks/tcp",
        "Transmission Control Protocol (TCP) - Links": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/subscribe/networks/tcp",
        "Transport Layer Security (TLS) - Mixed": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/security/tls",
        "Transport Layer Security (TLS) - Telegram Channels": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/channels/security/tls",
        "Transport Layer Security (TLS) - Links": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/subscribe/security/tls",
        "Non Transport Layer Security (Non-TLS) - Mixed": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/security/non-tls",
        "Non Transport Layer Security (Non-TLS) - Telegram Channels": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/channels/security/non-tls",
        "Non Transport Layer Security (Non-TLS) - Links": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/subscribe/security/non-tls",
        "Internet Protocol Version 4 (IPV4) - Mixed": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/layers/ipv4",
        "Internet Protocol Version 4 (IPV4) - Telegram Channels": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/channels/layers/ipv4",
        "Internet Protocol Version 4 (IPV4) - Links": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/subscribe/layers/ipv4",
        "Internet Protocol Version 6 (IPV6) - Mixed": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/layers/ipv6",
        "Internet Protocol Version 6 (IPV6) - Telegram Channels": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/channels/layers/ipv6",
        "Internet Protocol Version 6 (IPV6) - Links": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/subscribe/layers/ipv6",
        "آلبانی 🇦🇱": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/al/mixed",
        "آرژانتین 🇦🇷": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/ar/mixed",
        "ارمنستان 🇦🇲": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/am/mixed",
        "استرالیا 🇦🇺": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/au/mixed",
        "اتریش 🇦🇹": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/at/mixed",
        "بحرین 🇧🇭": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/bh/mixed",
        "بلاروس 🇧🇾": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/by/mixed",
        "بلژیک 🇧🇪": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/be/mixed",
        "بولیوی 🇧🇴": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/bo/mixed",
        "برزیل 🇧🇷": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/br/mixed",
        "بلغارستان 🇧🇬": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/bg/mixed",
        "کانادا 🇨🇦": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/ca/mixed",
        "چین 🇨🇳": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/cn/mixed",
        "کلمبیا 🇨🇴": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/co/mixed",
        "کرواسی 🇭🇷": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/hr/mixed",
        "قبرس 🇨🇾": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/cy/mixed",
        "چک 🇨🇿": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/cz/mixed",
        "دانمارک 🇩🇰": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/dk/mixed",
        "اکوادور 🇪🇨": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/ec/mixed",
        "استونی 🇪🇪": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/ee/mixed",
        "فنلاند 🇫🇮": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/fi/mixed",
        "فرانسه 🇫🇷": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/fr/mixed",
        "آلمان 🇩🇪": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/de/mixed",
        "جبل‌الطارق 🇬🇮": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/gi/mixed",
        "یونان 🇬🇷": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/gr/mixed",
        "گواتمالا �🇹": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/gt/mixed",
        "هنگ کنگ 🇭🇰": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/hk/mixed",
        "مجارستان 🇭🇺": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/hu/mixed",
        "ایسلند 🇮🇸": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/is/mixed",
        "هند 🇮🇳": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/in/mixed",
        "اندونزی 🇮🇩": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/id/mixed",
        "ایران 🇮🇷": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/ir/mixed",
        "عراق 🇮🇶": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/iq/mixed",
        "ایرلند 🇮🇪": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/ie/mixed",
        "اسرائیل 🇮🇱": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/il/mixed",
        "ایتالیا 🇮🇹": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/it/mixed",
        "ژاپن 🇯🇵": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/jp/mixed",
        "اردن 🇯🇴": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/jo/mixed",
        "قزاقستان 🇰🇿": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/kz/mixed",
        "کره جنوبی 🇰🇷": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/kr/mixed",
        "لتونی 🇱🇻": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/lv/mixed",
        "لیتوانی 🇱🇹": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/lt/mixed",
        "لوکزامبورگ 🇱🇺": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/lu/mixed",
        "مالزی 🇲🇾": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/my/mixed",
        "مالت 🇲🇹": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/mt/mixed",
        "مکزیک 🇲🇽": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/mx/mixed",
        "مولداوی 🇲🇩": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/md/mixed",
        "هلند 🇳🇱": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/nl/mixed",
        "نیوزیلند 🇳🇿": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/nz/mixed",
        "مقدونیه شمالی 🇲🇰": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/mk/mixed",
        "نروژ 🇳🇴": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/no/mixed",
        "نامشخص ❓": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/na/mixed",
        "عمان 🇴🇲": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/om/mixed",
        "پاکستان 🇵🇰": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/pk/mixed",
        "پاراگوئه 🇵🇾": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/py/mixed",
        "پرو 🇵🇪": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/pe/mixed",
        "فیلیپین 🇵🇭": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/ph/mixed",
        "لهستان 🇵🇱": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/pl/mixed",
        "پرتغال 🇵🇹": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/pt/mixed",
        "پورتوریکو 🇵🇷": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/pr/mixed",
        "رومانی 🇷🇴": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/ro/mixed",
        "روسیه 🇷🇺": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/ru/mixed",
        "صربستان 🇷🇸": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/rs/mixed",
        "سیشل 🇸🇨": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/sc/mixed",
        "سنگاپور 🇸🇬": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/sg/mixed",
        "اسلواکی 🇸🇰": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/sk/mixed",
        "اسلوونی 🇸🇮": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/si/mixed",
        "آفریقای جنوبی 🇿🇦": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/za/mixed",
        "اسپانیا 🇪🇸": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/es/mixed",
        "سوئد 🇸🇪": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/se/mixed",
        "سوئیس 🇨🇭": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/ch/mixed",
        "تایوان 🇹🇼": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/tw/mixed",
        "تایلند 🇹🇭": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/th/mixed",
        "ترکیه 🇹🇷": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/tr/mixed",
        "اوکراین 🇺🇦": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/ua/mixed",
        "امارات متحده عربی 🇦🇪": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/ae/mixed",
        "بریتانیا 🇬🇧": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/gb/mixed",
        "ایالات متحده 🇺🇸": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/us/mixed",
        "ویتنام 🇻🇳": "https://raw.githubusercontent.com/10ium/telegram-configs-collector/main/countries/vn/mixed"
    },
    
    "میهومو (کلش متا)": {
        "countries__RulePlus": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/free-mihomo-sub/Nearby_countries__RulePlus.yaml",
        "countries__NoRule": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/free-mihomo-sub/Nearby_countries__NoRule.yaml",
        "telegram-configs-collector": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/free-mihomo-sub/telegram-configs-collector.yaml",
        "Hinvpn": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/free-mihomo-sub/Hinvpn_mix_RulePlus.yaml",
        "config-fetcher": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/10ium/multi-proxy-config-fetcher.yaml",
        "MahsaFreeConfig-mci": "https://raw.githubusercontent.com/coldwater-10/Vpnclashfa/refs/heads/main/free-mihomo-sub/MahsaFreeConfig-mci.yaml",
        "MahsaFreeConfig-mtn": "https://raw.githubusercontent.com/coldwater-10/Vpnclashfa/refs/heads/main/free-mihomo-sub/MahsaFreeConfig-mtn.yaml",
        "MahsaFreeConfig-mix": "https://raw.githubusercontent.com/coldwater-10/Vpnclashfa/refs/heads/main/free-mihomo-sub/MahsaFreeConfig-mix.yaml",
        "V2Hub reality": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/10ium/V2Hub3_reality.yaml",
        "V2Hub shadowsocks": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/10ium/V2Hub3_shadowsocks.yaml",
        "V2Hub trojan": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/10ium/V2Hub3_trojan.yaml",
        "V2Hub vmess": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/10ium/V2Hub3_vmess.yaml",
        "Aggregator": "https://raw.githubusercontent.com/10ium/V2RayAggregator/refs/heads/master/Eternity.yml",
        "CollectorLite ss": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/10ium/ss_iran.yaml",
        "CollectorLite trojan": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/10ium/trojan_iran.yaml",
        "CollectorLite vmess": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/10ium/vmess_iran.yaml",
        "rayan_proxy": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/free-mihomo-sub/rayan_proxy.yaml",
        "roosterkid": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/free-mihomo-sub/roosterkid.yaml",
        "itsyebekhe_IR": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/free-mihomo-sub/itsyebekhe_IR.yaml",
        "itsyebekhe_mix": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/free-mihomo-sub/itsyebekhe_mix.yaml",
        "itsyebekhe_reality": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/free-mihomo-sub/itsyebekhe_reality.yaml",
        "itsyebekhe_xhttp": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/free-mihomo-sub/itsyebekhe_xhttp.yaml",
        "Maimengmeng": "hhttps://raw.githubusercontent.com/10ium/free-config/refs/heads/main/free-mihomo-sub/Maimengmeng.yaml",
        "Maimengmeng_AnyTLS": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/free-mihomo-sub/Maimengmeng_AnyTLS.yaml",
        "66.42.50.118": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/66.42.50.118.yaml",
        "Barabama/clashmeta": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/Barabama/clashmeta.yaml",
        "Barabama/ndnode": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/Barabama/ndnode.yaml",
        "Barabama/nodefree": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/Barabama/nodefree.yaml",
        "Barabama/v2rayshare": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/Barabama/v2rayshare.yaml",
        "HDYOU": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/HDYOU.yaml",
        "Mosifree-Reality": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/Mosifree-Reality.yaml",
        "MrMohebi_under_1500ms": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/MrMohebi_under_1500ms.yaml",
        "Ruk1ng001": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/Ruk1ng001.yaml",
        "SnapdragonLee_clash_config_extra_US": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/SnapdragonLee_clash_config_extra_US.yaml",
        "YuanZhang": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/YuanZhang.yaml",
        "anaer": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/anaer.yaml",
        "clashe.eu.org": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/clashe.eu.org.yaml",
        "ermaozi": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/ermaozi.yaml",
        "fast.lycorisrecoil.org": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/fast.lycorisrecoil.org.yaml",
        "firefoxmmx2": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/firefoxmmx2.yaml",
        "free18": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/free18.yaml",
        "lagzian/meta": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/lagzian/meta.yaml",
        "lagzian/mix": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/lagzian/mix.yaml",
        "lagzian/reality": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/lagzian/reality.yaml",
        "lagzian/trinity": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/lagzian/trinity.yaml",
        "lagzian/vmess": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/lagzian/vmess.yaml",
        "lagzian/vmess_tvc": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/lagzian/vmess_tvc.yaml",
        "liketolivefree": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/liketolivefree.yaml",
        "mfuu": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/mfuu.yaml",
        "moneyfly1/merged_proxies": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/moneyfly1/merged_proxies.yaml",
        "moneyfly1/merged_proxies_new": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/moneyfly1/merged_proxies_new.yaml",
        "moneyfly1/merged_warp_proxies": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/moneyfly1/merged_warp_proxies.yaml",
        "moneyfly1/merged_warp_proxies_new": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/moneyfly1/merged_warp_proxies_new.yaml",
        "peasoft.list/meta": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/peasoft.list/meta.yaml",
        "peasoft.list/yaml": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/peasoft.list/yaml",
        "proxypool.link": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/proxypool.link.yaml",
        "pxypool.131433": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/pxypool.131433.yaml",
        "ripaojiedian": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/ripaojiedian.yaml",
        "ronghuaxueleng/NoMoreWalls": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/ronghuaxueleng/NoMoreWalls.yaml",
        "ronghuaxueleng/cfmem": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/ronghuaxueleng/cfmem.yaml",
        "ronghuaxueleng/combine": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/ronghuaxueleng/combine.yaml",
        "ronghuaxueleng/pawdroid": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/ronghuaxueleng/pawdroid.yaml",
        "snakem982-clash/meta-2": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/snakem982-clash/meta-2.yaml",
        "snakem982-clash/meta": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/snakem982-clash/meta.yaml",
        "ts-sf": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/ts-sf.yaml",
        "tt.vg": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/tt.vg.yaml",
        "An0nymousTeam": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/%40An0nymousTeam.yaml",
        "DarkVPNpro2.txt": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/%40DarkVPNpro2.txt.yaml",
        "FREE2CONFIG_Vless.txt": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/%40FREE2CONFIG_Vless.txt.yaml",
        "proxy_kafee.txt": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/%40proxy_kafee.txt.yaml",
        "redfree8": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/%40redfree8.yaml",
        "v2ray_hidify.txt": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/%40v2ray_hidify.txt.yaml",
        "v2raybluecrystal": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/%40v2raybluecrystal.yaml",
        "Ashkan-m": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/Ashkan-m.yaml",
        "Epodonios": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/Epodonios.yaml",
        "Everyday-VPN": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/Everyday-VPN.yaml",
        "Leon406-hysteria2": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/Leon406-hysteria2.yaml",
        "Mosifree/RealityMosifree_Reality": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/Mosifree/RealityMosifree_Reality.yaml",
        "Mosifree/SS": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/Mosifree/SS.yaml",
        "Mosifree/T%252CH": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/Mosifree/T%25252CH.yaml",
        "Mosifree/Vless": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/Mosifree/Vless.yaml",
        "Mosifree/Vmess": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/Mosifree/Vmess.yaml",
        "NiREvil_SSTime": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/NiREvil_SSTime.yaml",
        "Rayan-Config/ALL": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/Rayan-Config/ALL.yaml",
        "Rayan-Config/H-I": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/Rayan-Config/H-I.yaml",
        "Rayan-Config/H-II": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/Rayan-Config/H-II.yaml",
        "Rayan-Config/H-III": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/Rayan-Config/H-III.yaml",
        "Rayan-Config/H-IV": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/Rayan-Config/H-IV.yaml",
        "Rayan-Config/H-V": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/Rayan-Config/H-V.yaml",
        "Rayan-Config/WG": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/Rayan-Config/WG.yaml",
        "ResistalProxy_server": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/ResistalProxy_server.yaml",
        "ShadowsocksM-MCI-Wifi": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/ShadowsocksM-MCI-Wifi.yaml",
        "Surfboardv2ray/IR": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/Surfboardv2ray/IR.yaml",
        "Surfboardv2ray/US": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/Surfboardv2ray/US.yaml",
        "Surfboardv2ray/bugfix": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/Surfboardv2ray/bugfix.yaml",
        "Surfboardv2ray/ipv6": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/Surfboardv2ray/ipv6.yaml",
        "Surfboardv2ray/mahsa": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/Surfboardv2ray/mahsa.yaml",
        "Surfboardv2ray/random": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/Surfboardv2ray/random.yaml",
        "Surfboardv2ray/udp": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/Surfboardv2ray/udp.yaml",
        "YuanZhang.v2ray": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/YuanZhang.v2ray.yaml",
        "amirparsaxs@xsfilternet": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/amirparsaxs%40xsfilternet.yaml",
        "freedomnet25500/free": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/freedomnet25500/free.yaml",
        "freedomnet25500/ss": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/freedomnet25500/ss.yaml",
        "hamedp-71/_openproxylist": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/hamedp-71/_openproxylist.yaml",
        "hamedp-71/hp": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/hamedp-71/hp.yaml",
        "hfarahani_pr": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/hfarahani_pr.yaml",
        "iPsycho1/iPsycho": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/iPsycho1/iPsycho.yaml",
        "iPsycho1/iPsycho_Test-Config": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/iPsycho1/iPsycho_Test-Config.yaml",
        "ivuxy.tech": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/ivuxy.tech.yaml",
        "joYAQx.mcsslk.xyz": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/joYAQx.mcsslk.xyz.yaml",
        "liketolivefree_sub": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/liketolivefree_sub.yaml",
        "miladtahanian_config": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/miladtahanian_config.yaml",
        "moeinkey_ssh": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/moeinkey_ssh.yaml",
        "muma16fx.netlify.app": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/muma16fx.netlify.app.yaml",
        "ndsphonemy/default": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/ndsphonemy/default.yaml",
        "ndsphonemy/hys-tuic": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/ndsphonemy/hys-tuic.yaml",
        "ndsphonemy/lt-sub": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/ndsphonemy/lt-sub.yaml",
        "ndsphonemy/my": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/ndsphonemy/my.yaml",
        "peasoft_list_raw": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/peasoft_list_raw.yaml",
        "qiaomenzhuanfx.netlify.app": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/qiaomenzhuanfx.netlify.app.yaml",
        "rb360full_Reza/2": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/rb360full_Reza/2.yaml",
        "rb360full_Reza/Collection": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/rb360full_Reza/Collection.yaml",
        "robin.nscl.ir": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/robin.nscl.ir.yaml",
        "roosterkid/V2RAY_BASE64": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/roosterkid/V2RAY_BASE64.yaml",
        "roosterkid/V2RAY_RAW": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/roosterkid/V2RAY_RAW.yaml",
        "sDTz6J.absslk.xyz": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/sDTz6J.absslk.xyz.yaml",
        "shabane/merged": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/shabane/merged.yaml",
        "shabane/ss": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/shabane/ss.yaml",
        "shabane/trojan": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/shabane/trojan.yaml",
        "shabane/vmess": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/shabane/vmess.yaml",
        "theGreatPeter_nodes": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/theGreatPeter_nodes.yaml",
        "tristan-deng_MyNodes": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/tristan-deng_MyNodes.yaml",
        "voken100g/online": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/voken100g/online.yaml",
        "voken100g/recent": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/voken100g/recent.yaml",
        "wudongdefeng_list_raw": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/wudongdefeng_list_raw.yaml",
        "xsfilternet.zaya.io": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/xsfilternet.zaya.io.yaml",
        "shadowmere.xyz": "https://raw.githubusercontent.com/10ium/MihomoSaz/main/Sublist/shadowmere.xyz.yaml"
    },
    
    "دی ان اس برای رفع تحریم بدون پروکسی میهومو (کلش متا)": {
        "shecan": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/dnsforgame/shecan.yml",
        "begzar": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/dnsforgame/begzar.yml",
        "electro": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/dnsforgame/electro.yml",
        "403": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/dnsforgame/403.yml",
        "radar game": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/dnsforgame/radar.yml",
        "shelter": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/dnsforgame/shelter.yml",
        "shelter-mobile": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/dnsforgame/shelter-mobile.yml",
        "mix": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/dnsforgame/all.yml",
        "controld": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/dnsforgame/controld.yml",
        "Level3": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/dnsforgame/Level3.yml",
        "AD-Blocker": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/dnsforgame/AD-Blocker.yml",
        "Adguard": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/dnsforgame/Adguard.yml",
        "Cloudflare": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/dnsforgame/Cloudflare.yml",
        "Google": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/dnsforgame/Google.yml",
        "LagSlayer": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/dnsforgame/LagSlayer.yml",
        "LagZero": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/dnsforgame/LagZero.yml",
        "NextDNS": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/dnsforgame/NextDNS.yml",
        "NTT": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/dnsforgame/NTT.yml",
        "OpenDNS": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/dnsforgame/OpenDNS.yml",
        "Rethinkdns": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/dnsforgame/Rethinkdns.yml",
        "Sprintlink": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/dnsforgame/Sprintlink.yml",
        "Comodo": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/dnsforgame/Comodo.yml",
        "DNSWatch": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/dnsforgame/DNSWatch.yml",
        "NordVPN": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/dnsforgame/NordVPN.yml",
        "Quad9": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/dnsforgame/Quad9.yml",
        "Surfshark": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/dnsforgame/Surfshark.yml",
        "UltraDNS": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/dnsforgame/UltraDNS.yml",
        "Verisign": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/dnsforgame/Verisign.yml",
        "Yandex": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/dnsforgame/Yandex.yml",
        "UncensoredDNS": "https://raw.githubusercontent.com/10ium/free-config/refs/heads/main/dnsforgame/UncensoredDNS.yml"
    }
};